create table books (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(150) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PRICE INT NOT NULL,
    FILE_PATH VARCHAR(200) NOT NULL
);

CREATE TABLE ORDERS (
    ID BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    EMAIL VARCHAR(100) NOT NULL,
    BOOK_ID INT NOT NULL,
    ORDER_STATUS ENUM("ACTIVE", "INACTIVE", "CANCELLED", "CLOSED") DEFAULT "INACTIVE",
    PAYMENT_STATUS BOOLEAN DEFAULT FALSE,
    DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_LAST_UPDATED TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_book_orders FOREIGN KEY (BOOK_ID) REFERENCES books(ID)
);